// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAACyTDMbz5v0J1Vy3wjZ3HQgTNOcXVwpo',
    appId: '1:536465457827:android:5bcf6ee649b4f05badb516',
    messagingSenderId: '536465457827',
    projectId: 'navi-care-b7a15',
    storageBucket: 'navi-care-b7a15.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ9cOxrvlZZA6id6bUAlKksQcT0NIaarc',
    appId: '1:536465457827:web:4de44afbe313426cadb516',
    messagingSenderId: '536465457827',
    projectId: 'navi-care-b7a15',
    authDomain: 'navi-care-b7a15.firebaseapp.com',
    storageBucket: 'navi-care-b7a15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4tkaoDp42jUqjDZHJ3sTHXu2IfMpAgX8',
    appId: '1:536465457827:ios:d74263afeb6c0139adb516',
    messagingSenderId: '536465457827',
    projectId: 'navi-care-b7a15',
    storageBucket: 'navi-care-b7a15.firebasestorage.app',
    iosBundleId: 'com.abthon.navithera.therapist',
  );

}